name: Release2
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: 7zip
        run: sudo apt-get install p7zip-full



      - name: Build project
        run: dotnet build --configuration Debug

      - name: Publish project
        run: dotnet publish --configuration Debug --output ./ConsoleApp1/bin/Debug/net8.0

      - name: create archive
        working-directory: ./ConsoleApp1/bin/Debug
        run: 7z a -t7z Recursion.7zip ./net8.0

      - name: Create Release 
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false 
          prerelease: false 

      - name: Upload Release Asset 
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ConsoleApp1/bin/Debug/Recursion.7zip 
          asset_name: Recursion.7zip 
          asset_content_type: application/7zip 
